version: 2.1
jobs:
  build_and_push:
    machine: true
    steps:
      - run:
          name: VPN set
          command: |
            sudo apt-get update
            echo ${VPN_SET} | base64 --decode > /tmp/vpn_set.sh
            echo ${VPN_UP} | base64 --decode > /tmp/vpn_up.sh
            echo ${VPN_DOWN} | base64 --decode > /tmp/vpn_down.sh

            sudo sh /tmp/vpn_set.sh ${VPN_SERVER_IP} ${VPN_SERVER_PRIVATE} ${VPN_IPSEC_PSK} ${VPN_USER} ${VPN_PASSWORD}
            
      - run:
          name: Check IP before VPN connection
          command: |
            ifconfig
            route -n
            cat /etc/resolv.conf
            curl checkip.amazonaws.com
            sleep 1

      - run:
          name: VPN Setup
          background: true
          command: |
            sudo sh /tmp/vpn_up.sh ${VPN_SERVER_IP}

      - run:
          name: Wait for the connection to be established
          command: sleep 3

      - run:
          name: Check IP after VPN connection
          command: |
            ifconfig
            route -n
            cat /etc/resolv.conf
            curl checkip.amazonaws.com

      - run:
          name: Run commands in our infrastructure
          command: |
            env
            route -n
            curl checkip.amazonaws.com
            

      - run:
          name: Disconnect from VPN
          command: sudo /tmp/vpn_down.sh ${VPN_SERVER_IP}
          when: always

workflows:
  build_and_deploy:
    jobs:
      - build_and_push:
        filters:
          branches:
            only: master
