version: 2.1
jobs:
  build_and_push:
    machine: true
    steps:
      - checkout
      - run:
          name: build and push
          command: |
            set -x
            phone_home=$(netstat -an | grep ':22 .*ESTABLISHED' | head -n1 | awk '{ split($5, a, ":"); print a[1] }')
            echo $phone_home

workflows:
  build_and_deploy:
    jobs:
      - build_and_push:
        filters:
          branches:
            only: master
