version: 2.2
jobs:
  build_and_push:
    machine: true
    steps:
      - run:
          name: Install OpenVPN
          command: |
            sudo apt-get update
            sudo apt-get install strongswan xl2tpd net-tools -y

      - run:
          name: Check IP before VPN connection
          command: |
            ifconfig
            route -n
            sudo netstat -anp
            cat /etc/resolv.conf
            curl checkip.amazonaws.com

      - run:
          name: VPN Setup
          background: true
          command: |
            cat > /etc/ipsec.conf <<EOF
            conn myvpn
              auto=add
              keyexchange=ikev1
              authby=secret
              type=transport
              left=%defaultroute
              leftprotoport=17/1701
              rightprotoport=17/1701
              right=${VPN_SERVER_IP}
              ike=aes128-sha1-modp2048
              esp=aes128-sha1
            EOF

            cat > /etc/ipsec.secrets <<EOF
            : PSK "${VPN_IPSEC_PSK}"
            EOF

            chmod 600 /etc/ipsec.secrets

            cat > /etc/xl2tpd/xl2tpd.conf <<EOF
            [lac myvpn]
            lns = ${VPN_SERVER_IP}
            ppp debug = yes
            pppoptfile = /etc/ppp/options.l2tpd.client
            length bit = yes
            EOF

            cat > /etc/ppp/options.l2tpd.client <<EOF
            ipcp-accept-local
            ipcp-accept-remote
            refuse-eap
            require-chap
            noccp
            noauth
            mtu 1280
            mru 1280
            noipdefault
            defaultroute
            usepeerdns
            connect-delay 5000
            name "${VPN_USER}"
            password "${VPN_PASSWORD}"
            EOF

            chmod 600 /etc/ppp/options.l2tpd.client

            mkdir -p /var/run/xl2tpd
            touch /var/run/xl2tpd/l2tp-control

            service strongswan restart
            service xl2tpd restart


      - run:
          name: Wait for the connection to be established
          command: sleep 30

      - run:
          name: Check IP after VPN connection
          command: |
            ifconfig
            route -n
            sudo netstat -anp
            cat /etc/resolv.conf
            curl checkip.amazonaws.com

      - run:
          name: Run commands in our infrastructure
          command: |
            # A command
            # Another command
            ipsec up myvpn

            echo "c myvpn" > /var/run/xl2tpd/l2tp-control

            ip route

            


      - run:
          name: Disconnect from OpenVPN
          command: sudo killall openvpn || true
          when: always

workflows:
  build_and_deploy:
    jobs:
      - build_and_push:
        filters:
          branches:
            only: master
