version: 2.1
jobs:
  build_and_push:
    machine: true
    steps:
      - checkout
      - run:
          name: build and push
          command: |
            set -x
            git clone git@github.com:daseul22/homepage.git
            env
workflows:
  build_and_deploy:
    jobs:
      - build_and_push:
        filters:
          branches:
            only: master