import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.scss"
import Link from "next/link"
import { getSortedPostsData } from "../lib/posts"
import Header from "./components/header"

export async function getStaticProps() {
	const allPostsData = getSortedPostsData()
	return {
		props: {
			allPostsData
		}
	}
}

export default function Home({ allPostsData }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
		</div>
	)
}
